<?php

namespace Tests\Feature;

use App\Models\Product;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class HomeTest extends TestCase
{
    use RefreshDatabase;

    protected $products;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        Product::factory()->count(3)->create();
        $this->products = Product::all();
    }

    public function test_it_visit_page_of_home()
    {
        $this->get('/')
            ->assertStatus(200)
            ->assertViewIs('home');
    }

    public function test_list_of_products_in_home()
    {
        $response = $this->get('/')
            ->assertOk();
        $response->assertViewHas('products', $this->products);
    }

}
