<?php

namespace Tests\Feature;

use App\BaseRepo\Order\OrderRepository;
use App\Http\Controllers\OrderController;
use App\Http\Requests\StoreOrderRequest;
use App\Models\Order;
use App\Models\Product;
use Faker\Factory;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Http\Request;
use Tests\TestCase;

class OrderControllerTest extends TestCase
{
    use RefreshDatabase;

    private $faker;
    protected $order;
    protected $product;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->order = new OrderRepository(new Order());

        $this->faker = Factory::create();
        Product::factory()->count(1)->create();
        $this->product = Product::first();
    }

    public function test_it_visit_create_orders()
    {
        $responser = $this->get('/orders/create/' . $this->product->id);
        $responser->assertOk();
    }

    public function test_product_in_create_orders()
    {
        $response = $this->get('/orders/create/' . $this->product->id);
        $response->assertOk();
        $response->assertViewHas('product', $this->product);
    }

    public function test_order_create()
    {
        $this->withoutMiddleware();
        $response = $this->post('orders/create', [
            '_token' => csrf_token(),
            'customer_name' => 'Miguel Lopez A',
            'customer_email' => 'lopezarizamiguel@gmail.com',
            'customer_mobile' => '3015575931',
            'product_id' => $this->product->id,
            'customer_address' => 'Carrera 9D # 124-248 Torre 5 Apt 805'
        ]);
        $order = Order::first();
        $response->assertStatus(302);
        $response->assertRedirect('/orders/checkout/' . $order->id);
    }

    /*public function test_produc_in_checkout_page()
    {
        $order = Order::create([
            '_token' => csrf_token(),
            'customer_name' => 'Miguel Lopez A',
            'customer_email' => 'lopezarizamiguel@gmail.com',
            'customer_mobile' => '3015575931',
            'product_id' => $this->product->id,
            'customer_address' => 'Carrera 9D # 124-248 Torre 5 Apt 805'
        ]);
        $order = $order->fresh();
        $response = $this->get('/orders/checkout/' . $order->id)
            ->assertOk();
        $response->assertViewHas('order', $order);
    }*/

    public function test_function_index()
    {
        $responser = $this->get(route('orders.list'));
        $responser->assertOk();
    }

    /*public function test_exception_index()
    {
        $this->expectException(\Exception::class);

        $mock = $this->createMock(OrderController::class);
        $mock->expects($this->once())
            ->method('index')
            ->willThrowException(new \Exception());

        (new OrderController())->index();
    }*/

    public function test_create_form()
    {
        $resp = $this->get(route('orders.create', ['121212sdsdasdasdasd']));
        $resp->assertStatus(500);
    }
}
