<?php

namespace Tests\Unit;

use App\BaseRepo\Order\OrderRepository;
use App\Models\Order;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class OrderRepositoryTest extends TestCase
{
    use RefreshDatabase;

    protected $order;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->order = new OrderRepository(new Order());
    }

    public function test_get_list_orders()
    {
        $this->assertInstanceOf(Collection::class, $this->order->all());
    }
}
