<?php

namespace Tests\Unit;


use App\BaseRepo\PaymentProcess\PaymentProcessRepository;
use App\Models\PaymentProcess;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class PaymentProcessRepositoryTest extends TestCase
{
    use RefreshDatabase;
    protected $paymentProcess;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->paymentProcess = new PaymentProcessRepository(new PaymentProcess());
    }

    public function test_list()
   {
       $this->assertInstanceOf(Collection::class, $this->paymentProcess->all());
   }

   public function test_delete()
   {
       PaymentProcess::factory(1)->create();
       $this->assertTrue($this->paymentProcess->delete(1));
   }
}
