<?php

namespace Tests\Unit;

use App\BaseRepo\Product\ProductRepository;
use App\Models\Product;
use Illuminate\Database\Eloquent\ModelNotFoundException;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class ProductRepositoryTest extends TestCase
{
    use RefreshDatabase;
    protected $product;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->product = new ProductRepository(new Product());
    }

    public function test_delete_product()
    {
        Product::factory(1)->create();
        $this->assertEquals(1, $this->product->delete(1));
    }

    public function test_find_exception()
    {
        $this->expectException(ModelNotFoundException::class);
        $this->product->find(1000);
    }

    public function test_create_order()
    {
        $product = $this->product->create([
            'name' => 'test',
            'description' => 'test',
            'price' => 'test',
            'active' => 'test',
            'photo' => 'test'
        ]);
        $this->assertInstanceOf(Product::class, $product);
    }

    public function test_update_order()
    {
        Product::factory(1)->create();
        $product = $this->product->find(1)->toArray();
        $result = $this->product->update($product, 1);
        $this->assertEquals(true, $result);
    }
}
